export const types = Object.freeze({
    // Sync
    BUCKWHEAT_START_FETCHING: 'BUCKWHEAT_START_FETCHING',
    BUCKWHEAT_STOP_FETCHING: 'BUCKWHEAT_STOP_FETCHING',
    BUCKWHEAT_FILL: 'BUCKWHEAT_FILL',
    BUCKWHEAT_SET_FETCHING_ERROR: 'BUCKWHEAT_SET_FETCHING_ERROR',
    BUCKWHEAT_SET_FILTERS: 'BUCKWHEAT_SET_FILTERS',
    BUCKWHEAT_SET_FILTERED_ITEMS: 'BUCKWHEAT_SET_FILTERED_ITEMS',

    // Async
    BUCKWHEAT_FETCH_ASYNC: 'BUCKWHEAT_FETCH_ASYNC',
})
