export const types = Object.freeze({
    // Sync
    BUCKWHEAT_START_FETCHING: 'BUCKWHEAT_START_FETCHING',
    BUCKWHEAT_STOP_FETCHING: 'BUCKWHEAT_STOP_FETCHING',
    BUCKWHEAT_FILL: 'BUCKWHEAT_FILL',
    BUCKWHEAT_SET_FETCHING_ERROR: 'BUCKWHEAT_SET_FETCHING_ERROR',
    BUCKWHEAT_SET_FILTER_VALUES: 'BUCKWHEAT_SET_FILTER_VALUES',
    BUCKWHEAT_SET_FILTERED_ITEMS: 'BUCKWHEAT_SET_FILTERED_ITEMS',
    BUCKWHEAT_SET_IS_FIRST_LOAD: 'BUCKWHEAT_SET_IS_FIRST_LOAD',

    // Async
    BUCKWHEAT_FETCH_ASYNC: 'BUCKWHEAT_FETCH_ASYNC',
})
